/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class updateJNI {
  public final static native void DEFAULT_DIR_set(String jarg1);
  public final static native String DEFAULT_DIR_get();
  public final static native void update_srcdir(String jarg1);
}
