/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class update {
  public static void setDEFAULT_DIR(String value) {
    updateJNI.DEFAULT_DIR_set(value);
  }

  public static String getDEFAULT_DIR() {
    return updateJNI.DEFAULT_DIR_get();
  }

  public static void update_srcdir(String path) {
    updateJNI.update_srcdir(path);
  }

}
