name:                agent-hs
version:             0.1.0.0
github:              "shakfu/agent-hs"
license:             BSD3
author:              "shakfu"
maintainer:          "me@org.com"
copyright:           "2023 shakfu"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/agent-hs#readme>

dependencies:
- base >= 4.7 && < 5
- network >= 2.2.1.7
- HTTP >= 4000.0.9
- text >= 1.2.5.0
- time >= 1.1.4
- regex-compat >= 0.92
- feed >= 0.3.8
- tagsoup >= 0.12.3
- blaze-html >= 0.4.2.0
- blaze-markup >= 0.5.1.0
- parallel-io >= 0.3.2


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  agent-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agent-hs

tests:
  agent-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agent-hs
