# A Chart of Account for a Construction Company

chart = [
    (110, 'Cash'),
    (120, 'Accounts Receivable-Trade'),
    (121, 'Accounts Receivable-Retention'),
    (130, 'Inventory'),
    (140, 'Costs and Profits in Excess of Billings'),
    (150, 'Notes Receivable'),
    (160, 'Prepaid Expenses'),
    (199, 'Other Current Assets'),

    (210, 'Building and Land'),
    (220, 'Construction Equipment'),
    (230, 'Trucks and Autos'),
    (240, 'Office Equipment'),
    (250, 'Less Acc. Depreciation'),
    (260, 'Capital Leases'),
    (299, 'Other Assets'),

    (310, 'Accounts Payable-Trade'),
    (311, 'Accounts Payable-Retention'),
    (320, 'Billings in Excess of Costs and Profits'),
    (330, 'Notes Payable'),
    (340, 'Accrued Payroll'),
    (341, 'Accrued Payables'),
    (342, 'Accrued Taxes'),
    (343, 'Accrued Insurance'),
    (344, 'Accrued Vacation'),
    (350, 'Capital Leases Payable'),
    (360, 'Warranty Reserves'),
    (379, 'Other Current Liabilities'),
    (380, 'Long-Term Liabilities'),

    (410, 'Capital Stock'),
    (420, 'Retained Earnings'),
    (430, 'Current Period Net Income'),

    (500, 'Revenue'),

    (610, 'Materials'),
    (620, 'Labor'),
    (630, 'Subcontract'),
    (640, 'Equipment'),
    (650, 'Other'),

    (710, 'Rent and Lease Payments'),
    (720, 'Depreciation'),
    (730, 'Repairs and Maintenance'),
    (740, 'Fuel and Lubrication'),
    (750, 'Taxes, Licenses, and Insurance'),
    (798, 'Equipment Costs Charged to Employees'),
    (799, 'Equipment Costs Charged to Jobs'),

    (805, 'Advertising'),
    (806, 'Promotion'),
    (810, 'Car and Truck Expenses'),
    (811, 'Computer and Office Furniture'),
    (812, 'Repairs and Maintenance'),
    (819, 'Depreciation'),
    (820, 'Employee Wages and Salaries'),
    (821, 'Employee Benefits'),
    (822, 'Employee Retirement'),
    (823, 'Employee Recruiting'),
    (824, 'Employee Training'),
    (825, 'Employee Taxes'),
    (830, 'Insurance'),
    (835, 'Taxes and Licenses'),
    (840, 'Office Supplies'),
    (841, 'Office Purchase'),
    (842, 'Office Rent'),
    (843, 'Office Utilities'),
    (844, 'Postage and Delivery'),
    (845, 'Janitorial and Cleaning'),
    (846, 'Telephone'),
    (850, 'Charitable Contributions'),
    (855, 'Dues and Memberships'),
    (860, 'Publications and Subscriptions'),
    (865, 'Legal and Professional Services'),
    (870, 'Meals and Entertainment'),
    (875, 'Travel'),
    (880, 'Bank Fees'),
    (881, 'Interest Expense'),
    (885, 'Bad Debts'),
    (891, 'Unallocated Labor'),
    (892, 'Unallocated Materials'),
    (893, 'Warranty Expense'),
    (898, 'Miscellaneous'),
    (899, 'Overhead Charged to Jobs'),

    (910, 'Other Income'),
    (920, 'Other Expense'),
    (950, 'Income Tax')
]